# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45f2ccc201d12df1c46d058ae412827dcef44950fb099aa7aa15c49e061f037f225b67c874fde776ecaedd318f2ad8612f1a02b46d1e299394bd5e31c4b0f810

test:
  secret_key_base: 31840953b6d47bae79bdf308f897457ef04e38eaa13a1bc564f85f30f6bf7d5feb422fd3b417602858b2b54e4cad0082c3cbe6cece53443a7dacd08818e2ae47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
